require 'rake'
require 'rspec/core/rake_task'

hosts = [
  {
    :name   => 'commitm-dev',
    :roles  => %w( base ap db )
  },
  {
    :name   => 'commitm-ap01',
    :roles  => %w( base ap )
  },
  {
    :name   => 'commitm-ap02',
    :roles  => %w( base ap )
  }
]

hosts = hosts.map do |host|
  {
    :name       => host[:name],
    :short_name => host[:name].split('.')[0],
    :roles      => host[:roles]
  }
end

desc "Run serverspec to all hosts"
task :serverspec => 'serverspec:all'

namespace :serverspec do
  task :all => hosts.map { |h| 'serverspec:' + h[:short_name] }
  hosts.each do |host|
    desc "Run serverspec to #{host[:name]}"
    RSpec::Core::RakeTask.new(host[:short_name].to_sym) do |t|
      ENV['TARGET_HOST'] = host[:name]
      t.pattern = 'spec/{' + host[:roles].join(',') + '}/*_spec.rb'
    end
  end
end
